### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by DIMKA4621** [OS-IS/ai201-mihajlenko_d#1]

**Comment by DIMKA4621** [comment]
![image](https://github.com/user-attachments/assets/d5f3ec6e-709c-4100-ba6b-eb8a31c98c7f)

**Comment by DIMKA4621** [comment]
![image](https://github.com/user-attachments/assets/68a0b93a-67ac-4e2c-9a20-a907d996ee0d)

**Comment by oleksandrblazhko** [comment]
треба показати знімки екранів для SSH

**Comment by DIMKA4621** [comment]
![image](https://github.com/user-attachments/assets/24034c0d-66e4-46e6-bfbc-f7cb27413e7b)

**Comment by DIMKA4621** [comment]
![image](https://github.com/user-attachments/assets/d3628887-20be-4556-a38a-94de9895e62f)
![image](https://github.com/user-attachments/assets/b0dbd549-5c80-4d85-9da1-2e81fb374d75)

**Comment by DIMKA4621** [comment]
![image](https://github.com/user-attachments/assets/b74ac94b-a5f5-440e-9774-33e332c88625)

**Comment by DIMKA4621** [comment]
Прикріпив потрібні скріни

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
