### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-mihajlenko_d#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
2) Відомо, що Git-система контроля версій використовує поняття “гілка” (branch). 
Поясніть, будь ласка, як використання такої “гілки” 
може підвищити безпеку процесів створення програмного продукту?

**Comment by DIMKA4621** [comment]
Використання гілок (branch) у Git підвищує безпеку процесів створення програмного продукту через ізоляцію змін.
Кожна гілка дозволяє розробникам працювати над новими функціями або виправленнями окремо від основної кодової бази. Це запобігає внесенню потенційно небезпечних або нестабільних змін у головну гілку. 
Крім того, гілки спрощують процес код-рев'ю та тестування, що допомагає виявити та виправити вразливості перед злиттям змін. 
Таким чином, використання гілок сприяє контролю якості та безпеці програмного забезпечення.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
